apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-mongo-depl
spec:
  selector:
    matchLabels:
      app: items-mongo
  template:
    metadata:
      labels:
        app: items-mongo
    spec:
      containers:
      - name: items-mongo
        image: mongo:4.4.6
---
apiVersion: v1
kind: Service
metadata:
  name: items-mongo-service
spec:
  selector:
    app: items-mongo
  ports:
  - port: 27017
    targetPort: 27017
    name: db